{
 "title": "SignalR",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "system_runtime_gc_committed", "legendFormat": "Committed" },
    { "expr": "dotnet_total_memory_bytes", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Total Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "system_runtime_gen_0_size", "legendFormat": "Gen0" },
    { "expr": "system_runtime_gen_1_size", "legendFormat": "Gen1" },
    { "expr": "system_runtime_gen_2_size", "legendFormat": "Gen2" },
    { "expr": "system_runtime_gc_heap_size", "legendFormat": "heap" }
   ]
  },
  {
   "title": "Current Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_current_requests{job=\"aiquiz-api\"}",
     "legendFormat": "aiquiz"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "process_num_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Players",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "targets": [
    { "expr": "player_total", "legendFormat": "Players" }
   ]
  },
  {
   "title": "Rooms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 8 },
   "targets": [
    { "expr": "room_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "lobby",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "lobby_total{job=\"aiquiz-api\"}",
     "legendFormat": "lobby"
    }
   ]
  },
  {
   "title": "SignalR Connection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_http_connections_signalr_server_active_connections",
     "legendFormat": "Active"
    }
   ]
  }
 ]
}